name: table_calendar_jalali
description: jalali table calendar
version: 1.0.0
homepage: https://github.com/erfaneillat/table-calendar-jalali

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shamsi_date: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
